### PR TITLE
NEI bookmarks compatibility

### PR DESCRIPTION
**Pull request by xchgeax**
Allows to save items displayed in a retrieval/crafting task to NEI bookmarks with Shift + LMB.

### CODE REVIEW

**Review by miozune — APPROVED** [review]
Maybe we can add keybind support. Click to see recipe and shift click to bookmark is a bit confusing.

**Comment by slprime** [comment]
why don't use ```codechicken.nei.guihook.IContainerObjectHandler``` interface? Then will be work standart NEI keyBinding & mouse click

**Comment by xchgeax** [comment]
> why don't use `codechicken.nei.guihook.IContainerObjectHandler` interface? Then will be work standart NEI keyBinding & mouse click

How do you expect it to work? It's methods are only fired in GuiContainerManager which expect GuiContainer and there is none of it involved.

**Comment by xchgeax** [comment]
> Maybe we can add keybind support. Click to see recipe and shift click to bookmark is a bit confusing.

Yeah `betterquesting.api2.client.gui.controls.PanelButton` does have `onKeyTyped(chac c, int keycode)Z` method which currently does nothing, Keybindings though are hardcoded inside `codechicken.nei.recipe.RecipeItemInputHandler` and we can't really nicely pass an itemstack to it.

**Pull request merged**
