### PR TITLE
Return to the quest book after viewing a recipe in NEI

### PR DESCRIPTION
**Pull request by SKProCH**
[Suggestion in discord](https://discord.com/channels/181078474394566657/181078474394566657/794253978669940776):
> have gone to NEI etc from a quest go back to the quest book

### CODE REVIEW

**Comment by Prometheus0000** [comment]
This already exists though? Just press backspace.

**Comment by SKProCH** [comment]
> This already exists though? Just press backspace.

It **should** return, but actually it just closes the gui. At least for me

**Comment by Prometheus0000** [comment]
Well, it worked for me?

**Review by Dream-Master — APPROVED** [review]

**Comment by repo-alt** [comment]
There is no harm in this workaround but looks like it is just hiding some bug on NEI side.

**Pull request merged**
