### PR TITLE
Refactor tasks

### PR DESCRIPTION
**Pull request by MuXiu1997**

### CODE REVIEW

**Comment by MuXiu1997** [comment]
@Dream-Master
If no one cares please close this pr

**Comment by eigenraven** [comment]
Can you explain a bit more what exactly did you do here? This is 4000 lines of code changes, and from a glance looks like a mix of formatting, method ordering changes with some actual rewritten code too, this makes it really difficult to review as a whole. The added `region`/`endregion` comments also seem out of place, it's probably some IDE thing that shouldn't live in the source tree

**Comment by Dream-Master** [comment]
@MuXiu1997

**Comment by MuXiu1997** [comment]
> looks like a mix of formatting, method ordering changes with some actual rewritten code too

I don't know how to do a summary, make these codes look more regular? i just did it on the way to finish another pr
I realised it was difficult to review and this pr is not important, so I closed it
The `region`/`endregion` comments, which I think is quite common, is used to fold the code

**Comment by eigenraven** [comment]
If you split the formatting changes (tabs/spaces, reordering methods, etc) from code changes into two commits I think it'd be much easier to review

**Comment by MuXiu1997** [comment]
You have a point, will do

**Review by eigenraven — APPROVED** [review]

**Pull request merged**
